In [1]:
import pandas as pd
import numpy as np
import scipy.stats as st
import os

In [13]:
import requests

url = 'https://raw.githubusercontent.com/stefannae/SIC-Artificial-Intelligence/main/SIC_AI_Coding_Exercises/SIC_AI_Chapter_04_Coding_Exercises/data_iris.csv'
response = requests.get(url)

with open('data_iris.csv', 'wb') as file:
    file.write(response.content)


In [15]:
df = pd.read_csv('data_iris.csv', header='infer')

In [17]:
df.shape

(150, 5)

In [19]:
df.head(3)

Sepal.Length  Sepal.Width  Petal.Length  Petal.Width Species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa

In [22]:
x = df['Petal.Length']
y = df['Sepal.Length']


In [34]:
np.round(st.pearsonr(x,y),3)  

array([0.872, 0.   ])

In [36]:
x.corr(y)

0.871753775886583

In [62]:
np.round(df.corr(),3)

ValueError: could not convert string to float: 'Jared Diamond'

In [42]:
np.round(st.spearmanr(x,y),3) 

array([0.882, 0.   ])

In [64]:
print(df.dtypes)


name          object
gender        object
age            int64
grade          int64
absence       object
bloodtype     object
height       float64
weight       float64
dtype: object


In [44]:
np.round(st.kendalltau(x,y),3) 

array([0.719, 0.   ])

In [66]:
numeric_df = df.select_dtypes(include=[float, int])


In [68]:
correlation_matrix = numeric_df.corr()
print(np.round(correlation_matrix, 3))


          age  grade  height  weight
age     1.000  0.834   0.345   0.523
grade   0.834  1.000   0.301   0.588
height  0.345  0.301   1.000   0.664
weight  0.523  0.588   0.664   1.000


In [48]:
import requests

url = 'https://raw.githubusercontent.com/stefannae/SIC-Artificial-Intelligence/main/SIC_AI_Coding_Exercises/SIC_AI_Chapter_04_Coding_Exercises/data_studentlist.csv'
response = requests.get(url)

# Lưu file vào thư mục hiện tại
with open('data_studentlist.csv', 'wb') as file:
    file.write(response.content)

print('File đã được tải xuống và lưu thành công!')


File đã được tải xuống và lưu thành công!


In [50]:
df = pd.read_csv('data_studentlist.csv', header='infer')

In [52]:
df.head(3)

name gender  age  grade absence bloodtype  height  weight
0   Jared Diamond      M   23      3       Y         O   165.3    68.2
1  Sarah O'Donnel      F   22      2       N        AB   170.1    53.0
2    Brian Martin      M   24      4       N         B   175.0    80.1

In [54]:
x = df.height
y = df.weight

In [56]:
n = len(x)
r = x.corr(y)
z = np.arctanh(r)
std_error_z = 1/np.sqrt(n-3)

In [58]:
{'low':np.tanh(z-st.norm.ppf(0.975)*std_error_z), 'high': np.tanh(z+st.norm.ppf(0.975)*std_error_z)}

{'low': 0.26960396330592223, 'high': 0.8677953581441814}

In [60]:
{'low':np.tanh(z-st.norm.ppf(0.995)*std_error_z), 'high': np.tanh(z+st.norm.ppf(0.995)*std_error_z)}

{'low': 0.11137578298592947, 'high': 0.9030812794020874}