In [5]:
import numpy as np
import tensorflow as tf 
np.set_printoptions(precision=3)
a = np.array([1,2,3],dtype=np.int32) 
b = [4, 5, 6]
t_a = tf.convert_to_tensor(a)
t_b = tf.convert_to_tensor(b)
t_one = tf.ones((2,3))
t_one.shape

TensorShape([2, 3])

In [7]:
tf.fill((4,3),1)

<tf.Tensor: shape=(4, 3), dtype=int32, numpy=
array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]], dtype=int32)>

In [9]:
tf.one_hot([0,2,3],5)

<tf.Tensor: shape=(3, 5), dtype=float32, numpy=
array([[1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.]], dtype=float32)>

In [11]:
tf.random.set_seed(42)
t1 = tf.random.uniform(shape=(5,2), minval=1.0, maxval=10)
t2 = tf.random.normal(shape=(5,2), mean=0.0, stddev=1.0)
print(t1)
print(t2)

tf.Tensor(
[[6.981 4.969]
 [4.176 5.18 ]
 [1.303 7.162]
 [7.661 8.852]
 [3.037 3.009]], shape=(5, 2), dtype=float32)
tf.Tensor(
[[ 8.422e-02 -8.609e-01]
 [ 3.781e-01 -5.196e-03]
 [-4.945e-01  6.178e-01]
 [-3.308e-01 -1.384e-03]
 [-4.237e-01 -1.387e+00]], shape=(5, 2), dtype=float32)


In [13]:
t = tf.multiply(t1,t2).numpy()
print(t)

[[ 0.588 -4.278]
 [ 1.579 -0.027]
 [-0.644  4.425]
 [-2.534 -0.012]
 [-1.287 -4.174]]


In [20]:
a=[1.2,3.4, 7.5, 4.1, 5.0, 1.0]
ds = tf.data.Dataset.from_tensor_slices(a) 
print(ds)
for i in ds:
    print(i) 
ds_batch = ds.batch(3)
for i, e in enumerate(ds_batch,100):
    print('batch{}:'.format(i), e.numpy())

<_TensorSliceDataset element_spec=TensorSpec(shape=(), dtype=tf.float32, name=None)>
tf.Tensor(1.2, shape=(), dtype=float32)
tf.Tensor(3.4, shape=(), dtype=float32)
tf.Tensor(7.5, shape=(), dtype=float32)
tf.Tensor(4.1, shape=(), dtype=float32)
tf.Tensor(5.0, shape=(), dtype=float32)
tf.Tensor(1.0, shape=(), dtype=float32)
batch100: [1.2 3.4 7.5]
batch101: [4.1 5.  1. ]


2024-08-14 14:08:41.009858: I tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence


In [22]:
tf.random.set_seed(42)
tx = tf.random.uniform([4,3], dtype=tf.float32) 
ty = tf.range(4)
dsX = tf.data.Dataset.from_tensor_slices(tx) 
dsY = tf.data.Dataset.from_tensor_slices(ty) 
ds_merge = tf.data.Dataset.zip((dsX,dsY))
for i in ds_merge:
    print('  x:   ', i[0].numpy(), '  y:  ', i[1].numpy())

  x:    [0.665 0.441 0.353]   y:   0
  x:    [0.464 0.034 0.685]   y:   1
  x:    [0.74  0.872 0.226]   y:   2
  x:    [0.223 0.31  0.722]   y:   3


In [26]:
tf.random.set_seed(1)
ds = ds_merge.shuffle(buffer_size=len(tx)) 
for i in ds:
    print('  x:  ', i[0].numpy(), '  y:  ', i[1].numpy())

  x:   [0.74  0.872 0.226]   y:   2
  x:   [0.464 0.034 0.685]   y:   1
  x:   [0.665 0.441 0.353]   y:   0
  x:   [0.223 0.31  0.722]   y:   3


In [32]:
ds = ds_merge.batch(batch_size=3, drop_remainder=False) 
batch_x, batch_y = next(iter(ds))
print('batch x: \n', batch_x.numpy())
print('batch y: \n', batch_y.numpy()) 
print('Bactch:\n')
for i in ds:
    print(i[0].numpy(),' ',i[1].numpy())

batch x: 
 [[0.665 0.441 0.353]
 [0.464 0.034 0.685]
 [0.74  0.872 0.226]]
batch y: 
 [0 1 2]
Bactch:

[[0.665 0.441 0.353]
 [0.464 0.034 0.685]
 [0.74  0.872 0.226]]   [0 1 2]
[[0.223 0.31  0.722]]   [3]


In [34]:
ds = ds_merge.batch(3).repeat(count=2) 
for i, (batchx,batchy) in enumerate(ds):
    print(i, batch_x.shape, batch_y.numpy())

0 (3, 3) [0 1 2]
1 (3, 3) [0 1 2]
2 (3, 3) [0 1 2]
3 (3, 3) [0 1 2]


2024-08-14 14:10:34.825008: I tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence


In [36]:
ds = ds_merge.shuffle(4).batch(2).repeat(20) 
for i, (batch_x, batch_y) in enumerate(ds):
        print(i, batch_x.shape, batch_y.numpy())

0 (2, 3) [1 2]
1 (2, 3) [3 0]
2 (2, 3) [1 3]
3 (2, 3) [0 2]
4 (2, 3) [2 1]
5 (2, 3) [3 0]
6 (2, 3) [0 1]
7 (2, 3) [2 3]
8 (2, 3) [0 3]
9 (2, 3) [1 2]
10 (2, 3) [0 1]
11 (2, 3) [3 2]
12 (2, 3) [3 0]
13 (2, 3) [1 2]
14 (2, 3) [1 3]
15 (2, 3) [0 2]
16 (2, 3) [0 2]
17 (2, 3) [3 1]
18 (2, 3) [3 1]
19 (2, 3) [2 0]
20 (2, 3) [3 2]
21 (2, 3) [0 1]
22 (2, 3) [2 0]
23 (2, 3) [3 1]
24 (2, 3) [3 2]
25 (2, 3) [0 1]
26 (2, 3) [0 3]
27 (2, 3) [1 2]
28 (2, 3) [0 1]
29 (2, 3) [2 3]
30 (2, 3) [3 0]
31 (2, 3) [1 2]
32 (2, 3) [1 3]
33 (2, 3) [2 0]
34 (2, 3) [3 1]
35 (2, 3) [0 2]
36 (2, 3) [1 2]
37 (2, 3) [0 3]
38 (2, 3) [3 0]
39 (2, 3) [1 2]
